name: ibis-omniscidb-dev
channels:
- nodefaults
- conda-forge

dependencies:

# core
- ibis-framework-core >=2
- pandas
- pyomnisci >=0.28.1
- pyomniscidb >=5.5.2
- pyarrow
- rbc >=0.4.0

# geo
- geopandas
- gdal
- shapely

# dev
- black
- pip <21.3
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- mock
- flake8
- flake8-comprehensions
- mypy
- isort
- pydocstyle
- setuptools-scm
