name: ibis-heavyai
channels:
- conda-forge
- defaults

dependencies:

# core
- python >=3.7
- ibis-framework-core >=2.0
- heavyai
- rbc >=0.8.0
- pyarrow
- regex
- pandas

# geo
- geopandas
- shapely

# dev
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- mock
