name: ibis-omniscidb-dev
channels:
- conda-forge
dependencies:

# core
- ibis  # TODO: require Ibis 2.0 when it's released
- pymapd>=0.24
- pyarrow>=0.15.0

# dev
- flake8
- mypy
- isort
- pydocstyle
- setuptools-scm
