name: ibis-omniscidb-dev
channels:
- conda-forge

dependencies:

# core
- pandas
- pyomnisci>=0.27.0
- pyomniscidb>=5.5.2
- pyarrow
# numpy 1.20 has conflicts with pandas and pyarrow
# pyarrow.lib.ArrowTypeError: ('Did not pass numpy.dtype object',
#   'Conversion failed for column salary with type float64')
- numpy<1.20
- rbc>=0.4.0
# ibis 1.4 for python 3.7 installs pymapd, and ibis-omniscidb
# doens't use pymapd anymore
- python 3.8.*

# TODO: sqlalchemy pinning should be removed when Ibis 2.0 is released
- sqlalchemy<1.4

# dev
- black
- pip
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- mock
- flake8
- flake8-comprehensions
- mypy
- isort
- pydocstyle
- setuptools-scm
