name: ibis-heavyai
channels:
- conda-forge
- defaults

dependencies:

# core
- python >=3.7
- ibis-framework-core <=3.0
- heavyai
- rbc
- numpy <= 1.23
- numba <= 0.56
- pyarrow
- regex
- pandas
- importlib_metadata
- packaging

# geo
- geopandas
- shapely

# dev
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- mock
