name: ibis-omniscidb
channels:
- nodefaults
- conda-forge

dependencies:

# core
- python >=3.7
- ibis-framework-core >2.0
- pandas
- heavyai >=6.0.0
- pyarrow
- rbc >=0.8.0

# geo
- geopandas
- gdal
- shapely

# dev
- black
- pip <21.3
- pre-commit
- pytest
- pytest-cov
- pytest-mock
