name: ibis-omniscidb-dev
channels:
- nodefaults
- conda-forge

dependencies:

# core
- numba <0.54
- pandas
- pyomnisci >=0.27.0
- pyomniscidb >=5.5.2
- pyarrow
- rbc >=0.4.0
- python 3.8.*
- sqlalchemy

# geo
- geopandas
- gdal

# dev
- black
- pip
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- mock
- flake8
- flake8-comprehensions
- mypy
- isort
- pydocstyle
- setuptools-scm
