version: '3'
services:

  omniscidb:
    image: omnisci/core-os-cpu:v5.3.0
    hostname: omniscidb
    ports:
      - 6274:6274
      - 6278:6278

  waiter:
    image: jwilder/dockerize
    command: dockerize -wait tcp://omniscidb:6274
