version: '3'
services:

  heavydb:
    image: heavyai/core-os-cpu
    hostname: heavydb
    ports:
      - 6274:6274
      - 6278:6278
    volumes:
      - ./heavydb.conf:/heavydb-storage/heavydb.conf

  waiter:
    image: jwilder/dockerize
    command: |
      dockerize -wait tcp://heavydb:6274
        -wait-retry-interval 5s
        -timeout 1m
