version: '3.9'
services:

  heavydb:
    image: heavyai/core-os-cpu
    hostname: heavydb
    ports:
      - 6274:6274
      - 6278:6278
    volumes:
      - ./heavydb.conf:/var/lib/heavyai/heavy.conf:ro

  waiter:
    image: jwilder/dockerize
    depends_on:
      - heavydb
    command: |
      dockerize -wait tcp://heavydb:6274
        -wait-retry-interval 5s
        -timeout 1m
